apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer # This type is used for Cloud clusters, while "NodePort" for local ones
# type: NodePort 